name: Push workflow

on:
  push:
    branches: [main, dev]

# concurrency:
#   group: push-${{ github.ref }}
#   cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  check:
    name: Check changes
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Yarn and Workspace cache
        uses: ./.github/actions/setup-workspace
        id: setup-workspace
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install
        if: steps.setup-workspace.outputs.cache-hit != 'true'

      - name: Check Nx affected
        uses: ./.github/actions/check-nx-affected
        with:
          branch: ${{ steps.setup-workspace.outputs.branch }}
